secure:
  white-list: /login
  rule-list:
    - path: /interceptor
      method: GET
      expression: "hasPermission('user::list::delete')"
    - path: /method
      method: GET
      expression: "anon()"